"""Add completed_at to sorting_batches

Revision ID: 61335dd29c2a
Revises: 6e46fe897a23
Create Date: 2025-11-24 22:44:26.316961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61335dd29c2a'
down_revision = '6e46fe897a23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sorting_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sorting_batches', schema=None) as batch_op:
        batch_op.drop_column('completed_at')

    # ### end Alembic commands ###
